{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.cruciblemc",
    "module": "CrucibleGradle",
    "version": "1.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.anatawa12.forge",
          "module": "ForgeGradle",
          "version": {
            "requires": "1.2-1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "CrucibleGradle-1.2-SNAPSHOT.jar",
          "url": "CrucibleGradle-1.2-SNAPSHOT.jar",
          "size": 2354163,
          "sha512": "557da6008ba28df30940e3c1756a58cf5d953daea6118128333099d77d52a65d80e3695c7b38b53a032dd3a0a8552dd7806ce89a50e404713538421c2ebc2689",
          "sha256": "363a100b0646bebb1a61c6ed96769d31b3563689d0a51af04f6d0c97a49a4966",
          "sha1": "c391055bdc90db8eac11c2cdeb9e2e1d9182d119",
          "md5": "677d8621bef195fd27d08ecc9883225f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.opencsv",
          "module": "opencsv",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "com.cloudbees",
          "module": "diff4j",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.github.abrarsyed.jastyle",
          "module": "jAstyle",
          "version": {
            "requires": "1.2"
          }
        },
        {
          "group": "net.sf.trove4j",
          "module": "trove4j",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.nothome",
          "module": "javaxdelta",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.anatawa12.forge",
          "module": "SpecialSource",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.14"
          }
        },
        {
          "group": "de.oceanlabs.mcp",
          "module": "RetroGuard",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "de.oceanlabs.mcp",
          "module": "mcinjector",
          "version": {
            "requires": "3.2-SNAPSHOT"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "Srg2Source",
          "version": {
            "requires": "4.2.7"
          }
        },
        {
          "group": "com.github.tony19",
          "module": "named-regexp",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "com.anatawa12.forge",
          "module": "ForgeGradle",
          "version": {
            "requires": "1.2-1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "CrucibleGradle-1.2-SNAPSHOT.jar",
          "url": "CrucibleGradle-1.2-SNAPSHOT.jar",
          "size": 2354163,
          "sha512": "557da6008ba28df30940e3c1756a58cf5d953daea6118128333099d77d52a65d80e3695c7b38b53a032dd3a0a8552dd7806ce89a50e404713538421c2ebc2689",
          "sha256": "363a100b0646bebb1a61c6ed96769d31b3563689d0a51af04f6d0c97a49a4966",
          "sha1": "c391055bdc90db8eac11c2cdeb9e2e1d9182d119",
          "md5": "677d8621bef195fd27d08ecc9883225f"
        }
      ]
    }
  ]
}
